version: "1.0"
name: carpooling
services:
  web:
    image: tomcat:9.0.71-jre8-temurin-focal
    ports:
      - "80:8080"
    command: >
      bash -c "catalina.sh run"
    volumes:
      - ../target/CarPooling-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - database
      - api
  database:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=gigachungus
    volumes:
      - ./database/database-structure.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./database/data:/var/lib/mysql
  api:
    image: node
    volumes:
      - ./api:/project
    working_dir: /project
    command: >
      bash -c "npm install && node index.js"